# Generated by Django 4.2 on 2023-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XlsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowID', models.PositiveBigIntegerField()),
                ('company', models.CharField(max_length=100)),
                ('fact_qlig_data1', models.IntegerField()),
                ('fact_qlig_data2', models.IntegerField()),
                ('fact_qoil_data1', models.IntegerField()),
                ('fact_qoil_data2', models.IntegerField()),
                ('forecast_qlig_data1', models.IntegerField()),
                ('forecast_qlig_data2', models.IntegerField()),
                ('forecast_qoil_data1', models.IntegerField()),
                ('forecast_qoil_data2', models.IntegerField()),
            ],
        ),
    ]
